name = input("what's your name?:")
print ("Welcome to learning python "+name)
age = input("How old are you?")
print("You are so cool")
replit = input("do you like coding")
print("lol")

print()
print("So, you are")
print(name)
print("and are the ripe old age of")
print(age)
print("and clearly think that Replit is")
print(replit)

print("Definitely not a Phishing Scam")
print()
input("Your Name")
print("Thanks for logging in")
print(name)
cardNumber = input("What is your credit card number?")
print("Thanks, I definitely wont put")
print("cardNumber")
print("into Amazon and order anything weird")
print()
print("Promise")
maidenName =input("What is your Mother's maiden name? ")
print()
print("That's cool, I just wanted to know that")
print(maidenName)
print("was your Mum's maiden name. Not because the bank requested it or anything, honest.")
